fix messag

diff --git a/bin/git/gcheckout b/bin/git/gcheckout
--- a/bin/git/gcheckout
+++ b/bin/git/gcheckout
@@ -1,2 +1,4 @@
 #! /bin/bash
-git checkout $1
+source "$(dirname "$0")/.gitrc"
+echo -e "$GIT_TAG Checking out $1..."
+git checkout $1 && echo -e "$GIT_TAG_OK On branch $1" || echo -e "$GIT_TAG_ERR Checkout failed."
diff --git a/bin/git/gcom b/bin/git/gcom
--- a/bin/git/gcom
+++ b/bin/git/gcom
@@ -1,4 +1,4 @@
 #! /bin/bash
-echo -e "\033[1;34m[GIT]\033[0m COMMIT..."
-git commit -m $1
-
+source "$(dirname "$0")/.gitrc"
+echo -e "$GIT_TAG Committing..."
+git commit -m "$1" && echo -e "$GIT_TAG_OK Committed." || echo -e "$GIT_TAG_ERR Commit failed."
diff --git a/bin/git/gfetch b/bin/git/gfetch
--- a/bin/git/gfetch
+++ b/bin/git/gfetch
@@ -1,4 +1,4 @@
 #! /bin/bash
-echo -e "\033[1;34m[GIT]\033[0m Fetching..."
-git fetch
-
+source "$(dirname "$0")/.gitrc"
+echo -e "$GIT_TAG Fetching..."
+git fetch && echo -e "$GIT_TAG_OK Fetch complete." || echo -e "$GIT_TAG_ERR Fetch failed."
diff --git a/bin/git/gpop b/bin/git/gpop
--- a/bin/git/gpop
+++ b/bin/git/gpop
@@ -1,3 +1,4 @@
 #! /bin/bash
-echo -e "\033[1;34m[GIT]\033[0m Popping changes..."
-git stash pop
+source "$(dirname "$0")/.gitrc"
+echo -e "$GIT_TAG Popping changes..."
+git stash pop && echo -e "$GIT_TAG_OK Stash applied." || echo -e "$GIT_TAG_ERR Stash pop failed."
diff --git a/bin/git/gpush b/bin/git/gpush
--- a/bin/git/gpush
+++ b/bin/git/gpush
@@ -1,21 +1,22 @@
 #!/bin/bash
+source "$(dirname "$0")/.gitrc"
 
 branch=$1
 
 if [[ -z "$branch" ]]; then
     branch=$(git rev-parse --abbrev-ref HEAD)
-    echo -e "\033[1;34m[GIT]\033[0m No branch specified, using current: $branch"
+    echo -e "$GIT_TAG No branch specified, using current: $branch"
 fi
 
 remotes=($(git remote))
 
 if [[ ${#remotes[@]} -eq 0 ]]; then
-    echo -e "\033[1;34m[GIT]\033[0m No remotes configured."
+    echo -e "$GIT_TAG_ERR No remotes configured."
     exit 1
 elif [[ ${#remotes[@]} -eq 1 ]]; then
     remote="${remotes[0]}"
 else
-    echo -e "\033[1;34m[GIT]\033[0m Multiple remotes found:"
+    echo -e "$GIT_TAG Multiple remotes found:"
     for i in "${!remotes[@]}"; do
         url=$(git remote get-url "${remotes[$i]}")
         echo "  [$i] ${remotes[$i]} ($url)"
@@ -23,12 +24,10 @@ else
     read -rp "Select remote [0-$((${#remotes[@]}-1))]: " choice
     remote="${remotes[$choice]}"
     if [[ -z "$remote" ]]; then
-        echo -e "\033[1;34m[GIT]\033[0m Invalid selection."
+        echo -e "$GIT_TAG_ERR Invalid selection."
         exit 1
     fi
 fi
 
-echo -e "\033[1;34m[GIT]\033[0m Pushing $branch to $remote..."
-git push -u "$remote" "$branch"
-
-
+echo -e "$GIT_TAG Pushing $branch to $remote..."
+git push -u "$remote" "$branch" && echo -e "$GIT_TAG_OK Pushed." || echo -e "$GIT_TAG_ERR Push failed."
diff --git a/bin/git/gsave b/bin/git/gsave
--- a/bin/git/gsave
+++ b/bin/git/gsave
@@ -1,4 +1,4 @@
 #! /bin/bash
-echo -e "\033[1;34m[GIT]\033[0m Stashing changes..."
-git stash save
-
+source "$(dirname "$0")/.gitrc"
+echo -e "$GIT_TAG Stashing changes..."
+git stash save && echo -e "$GIT_TAG_OK Stashed." || echo -e "$GIT_TAG_ERR Stash failed."
